# Generated by Django 3.2.5 on 2021-07-27 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmovie', 'usersMine'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('language', models.CharField(choices=[('EN', 'ENGLISH'), ('GR', 'GERMAN')], max_length=2)),
                ('status', models.CharField(choices=[("Eng ko'p ko'rilgan", "Eng ko'p ko'rilgan"), ("Eng ko'p yuklangan", "Eng ko'p yuklangan"), ('Eng reytingi baland', 'Eng reytingi baland')], max_length=50)),
                ('year_of_production', models.DateField()),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('views_count', models.IntegerField(default=0)),
            ],
        ),
    ]
