# Generated by Django 3.2.5 on 2021-08-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmovie', '0007_usermine_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermine',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
